# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NicFitMTG
description: Legacy Nic Fit
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicfitmtg.com"

destination: ./build

short_date_format: "%b %e"
long_date_format: "%b %e, %Y"

include:
  - _pages

permalink: /posts/:title/

collections:
  authors:
    output: true
  categories:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - title: About
    page: _pages/about.md
  - title: Archetypes
    page: _pages/archetypes.md
    #submenu:
    #  # Comment page above to enable this
    #  - title: JunkFit
    #    page: _pages/archetypes/junkfit.md
  - title: Sideboarding
    page: _pages/sideboarding.md
  - title: Matchups
    page: _pages/matchups.md
#  - title: Shop
#    url: "http://example.com"

social:
  # This Twitter account is secured but there isn't much there yet
  # twitter: NicFitMTG
  discord: https://discordapp.com/invite/5R6KBa5
  youtube: https://www.youtube.com/channel/UCu8BOWZv-D2Xh6teXqL-ttw

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - webpack.config.js
  - package.json
  - package-lock.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Pagination
# https://github.com/sverrirs/jekyll-paginate-v2/
# ------------------------------------------------------------
pagination:
  enabled: true
  collection: "posts"
  permalink: "/posts/page/:num/"
  title: ":title"
  sort_field: "date"
  sort_reverse: true
  per_page: 10
