name: Build and validate Jekyll site

on: push

jobs:
  build_and_test:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jerryjvl/jekyll-build-action@v1

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v0.4.4
      with:
        root: build/
        log_level: INFO
        extra: --show-warnings
