name: Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Build Jekyll and Deploy to GitHub Pages
      uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.JEKYLL_PAT }}
